[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["vendor"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
remappings = ["openzeppelin-contracts/=vendor/openzeppelin/contracts/", "forge-std/=vendor/openzeppelin/lib/forge-std/src/"]
[fuzz]
runs = 256
